ARG NODE_VERSION=22.13.0

FROM node:${NODE_VERSION}-slim AS base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base AS build

COPY --link package.json package-lock.json ./
RUN npm install

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD [ "npm", "run", "dev" ]